#!/usr/bin/env python3
"""PreToolUse gate — generic, profile-driven.

Forces a confirmation prompt (or hard-denies) on dangerous Bash commands,
inspecting the FULL command string so chained forms like
`cd apps/api && node ace migration:run` are caught — something prefix-based
permission rules in settings.json miss.

Patterns come from `.claude/gate-config.json` (generated by /cohorte-init-pipeline from
the PIPELINE.md `gate` block):

    { "deny": ["node ace migration:fresh", ...],
      "ask":  ["git commit", "git push", "node ace migration:run", ...] }

A pattern matches a command segment when the segment *contains* the pattern
(after normalizing whitespace). `deny` wins over `ask`. If the config is missing
or unreadable, the hook stays silent (exit 0) and lets settings.json decide.

The hook fires for EVERY agent in the session — the lead, /cohorte-build's implementers,
and subagents spawned by the Workflow runtime alike. Workflow subagents run in
acceptEdits regardless of the session's permission mode (their Write/Edit calls
are auto-approved), but acceptEdits does NOT auto-approve Bash or Task, so this
gate still sees and can block them. In bypassPermissions (headless `claude -p`,
dashboard actions) there is no human to answer a prompt, so every `ask` match is
escalated to a hard deny with the reason attached — a clear refusal beats a
prompt that can never be answered.

Two extra duties beyond Bash patterns:

- Phase gate (`preflight` block in gate-config.json): a Task dispatch of a
  listed subagent_type (default review) requires a fresh
  `.claude/preflight.ok` stamp, written by pipeline/scripts/preflight.sh when
  typecheck+lint+tests are green. Stale/missing stamp => "ask" — dispatching
  reviewers onto code that doesn't compile burns their whole run. Freshness is
  a content digest (see tree_digest), not the HEAD sha: the reviewed tree is
  normally dirty, so a commit must not invalidate a stamp and an uncommitted
  edit must. The stamp is local and gitignored — never versioned.

Protocol: reads the PreToolUse payload on stdin; emits a JSON permissionDecision
of "deny" or "ask" on a match; otherwise exits 0 silently.
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

SPLIT = re.compile(r"&&|\|\||[;|\n]")
WS = re.compile(r"\s+")


def project_root() -> str:
    return os.environ.get("CLAUDE_PROJECT_DIR", ".")


def load_config() -> dict:
    path = os.path.join(project_root(), ".claude", "gate-config.json")
    empty = {"deny": [], "ask": [], "ask_on_default_branch": [], "default_branch": "main",
             "preflight": {}}
    try:
        with open(path, "r", encoding="utf-8") as fh:
            cfg = json.load(fh)
    except Exception:
        return empty
    preflight = cfg.get("preflight")
    if not isinstance(preflight, dict):
        preflight = {}
    return {
        "deny": list(cfg.get("deny", [])),
        "ask": list(cfg.get("ask", [])),
        # Patterns gated ONLY on the default branch — allowed freely on feature branches.
        "ask_on_default_branch": list(cfg.get("ask_on_default_branch", [])),
        "default_branch": cfg.get("default_branch", "main") or "main",
        # Phase gate: {"enabled": true, "agents": ["review"], "max_age_minutes": 30}
        "preflight": preflight,
    }


def norm(s: str) -> str:
    return WS.sub(" ", s.strip())


def session_cwd(payload: dict) -> str:
    """Where the gated command actually runs. A feature worktree is its own
    checkout — resolving git state in CLAUDE_PROJECT_DIR (the main checkout)
    would gate every worktree command as if it ran on the default branch."""
    return payload.get("cwd") or project_root()


def current_branch(cwd: str):
    """The checked-out branch at `cwd`, or None (not a repo / detached / git absent)."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=cwd, capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0:
            return out.stdout.strip() or None
    except Exception:
        pass
    return None


def known_heads(cwd: str):
    """Every HEAD sha this repo currently has checked out: `cwd`'s plus each
    linked worktree's. The preflight may legitimately have run in a feature
    worktree while the Task dispatch fires from the main checkout (or vice
    versa) — comparing against a single HEAD flags those runs as stale."""
    heads = set()
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=cwd, capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0 and out.stdout.strip():
            heads.add(out.stdout.strip())
    except Exception:
        pass
    try:
        out = subprocess.run(
            ["git", "worktree", "list", "--porcelain"],
            cwd=cwd, capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0:
            for line in out.stdout.splitlines():
                if line.startswith("HEAD "):
                    heads.add(line.split(" ", 1)[1].strip())
    except Exception:
        pass
    return heads


def worktree_dirs(cwd: str):
    """`cwd` plus every linked worktree path — the checkouts a stamp may describe."""
    dirs = [cwd]
    try:
        out = subprocess.run(
            ["git", "worktree", "list", "--porcelain"],
            cwd=cwd, capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0:
            for line in out.stdout.splitlines():
                if line.startswith("worktree "):
                    p = line.split(" ", 1)[1].strip()
                    if p and p not in dirs:
                        dirs.append(p)
    except Exception:
        pass
    return dirs


def tree_digest(cwd: str):
    """The digest pipeline/scripts/preflight.sh stamps for the checkout at `cwd`: the git
    tree id of the working tree, computed in a throwaway index (`.claude` and `specs`
    excluded — the pipeline writes those itself). Content-addressed, so a commit of the
    same code keeps the stamp valid and any real edit invalidates it. Must stay identical
    to the shell side. Returns None when git can't answer, and the caller falls back."""
    tmp = None
    try:
        idx = subprocess.run(
            ["git", "rev-parse", "--absolute-git-dir"],
            cwd=cwd, capture_output=True, text=True, timeout=3,
        )
        if idx.returncode != 0:
            return None
        real_index = os.path.join(idx.stdout.strip(), "index")
        fd, tmp = tempfile.mkstemp(prefix="cohorte-idx-")
        os.close(fd)
        # Seed from the real index to keep its stat cache — `add` then re-hashes only
        # what changed instead of the whole tree on every dispatch.
        if os.path.exists(real_index):
            shutil.copyfile(real_index, tmp)
        else:
            os.unlink(tmp)  # a 0-byte index is a corrupt index — let git create it
        env = dict(os.environ, GIT_INDEX_FILE=tmp)
        # Drop the excluded paths outright — an `add` exclude only stops them being
        # *updated*, so already-tracked ones would still shift the tree id.
        subprocess.run(
            ["git", "rm", "--cached", "-r", "-q", "--ignore-unmatch", "--", ".claude", "specs"],
            cwd=cwd, capture_output=True, timeout=10, env=env,
        )
        add = subprocess.run(
            ["git", "add", "-A", "--", ".", ":(exclude).claude", ":(exclude)specs"],
            cwd=cwd, capture_output=True, timeout=30, env=env,
        )
        if add.returncode != 0:
            return None
        out = subprocess.run(
            ["git", "write-tree"], cwd=cwd, capture_output=True, text=True, timeout=10, env=env,
        )
        if out.returncode != 0:
            return None
        return out.stdout.strip() or None
    except Exception:
        return None
    finally:
        for p in ((tmp, tmp + ".lock") if tmp else ()):
            try:
                os.unlink(p)
            except Exception:
                pass


def known_digests(cwd: str):
    """Every checkout's current digest. The preflight may have run in a feature worktree
    while the Task dispatch fires from the main checkout (or vice versa) — same reason
    known_heads() spans worktrees."""
    return {d for d in (tree_digest(p) for p in worktree_dirs(cwd)) if d}


def check_preflight(payload: dict, cfg: dict) -> int:
    """Phase gate on Task dispatches: review agents need a green preflight stamp."""
    pf = cfg.get("preflight") or {}
    if not pf.get("enabled"):
        return 0
    agents = pf.get("agents") or ["review"]
    subagent = (payload.get("tool_input") or {}).get("subagent_type", "") or ""
    if subagent not in agents:
        return 0

    stamp = os.path.join(project_root(), ".claude", "preflight.ok")
    why = None
    try:
        with open(stamp, "r", encoding="utf-8") as fh:
            raw = fh.read().strip()
    except Exception:
        raw = None
        why = "no preflight stamp found"
    if raw is not None:
        try:
            fields = raw.split()
            epoch_s = fields[0]
            sha = fields[1] if len(fields) > 1 else ""
            digest = fields[2] if len(fields) > 2 else ""
            age_min = (time.time() - float(epoch_s)) / 60
            max_age = float(pf.get("max_age_minutes", 30) or 30)
            cwd = session_cwd(payload)
            if age_min > max_age:
                why = f"the preflight stamp is {age_min:.0f} min old (max {max_age:.0f})"
            elif digest not in ("", "none"):
                # 2.0.0+ stamp: key off the verified CONTENT, not HEAD. A commit that
                # doesn't touch code keeps the stamp valid; an edit that never reaches a
                # commit invalidates it — both of which the sha comparison got backwards.
                digests = known_digests(cwd)
                if digests and digest not in digests:
                    why = "the code changed since the preflight ran"
            else:
                # Pre-2.0.0 stamp (no digest) — fall back to the HEAD comparison.
                heads = known_heads(cwd)
                if heads and sha not in ("", "none") and sha not in heads:
                    why = "HEAD moved since the preflight ran"
        except Exception:
            why = "the preflight stamp is unreadable (expected `<epoch> <sha> <digest>`)"
    if why is None:
        return 0
    # Same rule as the Bash gate: unattended runs have nobody to answer an "ask".
    unattended = payload.get("permission_mode") == "bypassPermissions"
    return decide(
        "deny" if unattended else "ask",
        f"Phase gate: dispatching `{subagent}` but {why}. Run the deterministic pre-flight first "
        f"(pipeline/scripts/preflight.sh — typecheck + lint + tests) so agents never review red code; "
        f"or confirm to dispatch anyway (PIPELINE.md gate.preflight)."
        + (" (denied outright: unattended run, nobody to confirm)" if unattended else ""),
    )


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # malformed input → don't block

    tool = payload.get("tool_name")
    cfg = load_config()

    if tool == "Task":
        return check_preflight(payload, cfg)
    if tool != "Bash":
        return 0

    command = (payload.get("tool_input") or {}).get("command", "") or ""
    deny, ask, branch_gated = cfg["deny"], cfg["ask"], cfg["ask_on_default_branch"]
    default = cfg["default_branch"]
    if not deny and not ask and not branch_gated:
        return 0

    # No human can answer a prompt in bypassPermissions (headless runs) — an "ask"
    # there either hangs or silently auto-resolves, so escalate it to a clear deny.
    unattended = payload.get("permission_mode") == "bypassPermissions"
    ask_decision = "deny" if unattended else "ask"
    ask_suffix = " (denied outright: unattended run, nobody to confirm)" if unattended else ""

    # Branch-conditional patterns (e.g. git/docker) are gated only on the default branch;
    # on a feature branch they run freely. Unknown branch (no repo / detached / no git) ⇒
    # be conservative and gate. Resolve the branch once, lazily.
    on_default = False
    if branch_gated:
        branch = current_branch(session_cwd(payload))
        on_default = branch is None or branch == default

    for raw in SPLIT.split(command):
        seg = norm(raw)
        if not seg:
            continue
        for pat in deny:
            if norm(pat) in seg:
                return decide("deny", f"`{pat}` is forbidden by the project's PIPELINE.md gate.")
        for pat in ask:
            if norm(pat) in seg:
                return decide(ask_decision,
                              f"`{pat}` is a gated command — confirm first (PIPELINE.md gate)."
                              f"{ask_suffix}")
        if on_default:
            for pat in branch_gated:
                if norm(pat) in seg:
                    return decide(ask_decision,
                                  f"`{pat}` is gated on the default branch `{default}` — confirm "
                                  f"(PIPELINE.md gate). It runs freely on feature branches."
                                  f"{ask_suffix}")

    return 0


def decide(decision: str, reason: str) -> int:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": decision,
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
