#!/usr/bin/env python3
"""PreToolUse gate — generic, profile-driven.

Forces a confirmation prompt (or hard-denies) on dangerous Bash commands,
inspecting the FULL command string so chained forms like
`cd apps/api && node ace migration:run` are caught — something prefix-based
permission rules in settings.json miss.

Patterns come from `.claude/gate-config.json` (generated by /init-pipeline from
the PIPELINE.md `gate` block):

    { "deny": ["node ace migration:fresh", ...],
      "ask":  ["git commit", "git push", "node ace migration:run", ...] }

A pattern matches a command segment when the segment *contains* the pattern
(after normalizing whitespace). `deny` wins over `ask`. If the config is missing
or unreadable, the hook stays silent (exit 0) and lets settings.json decide.

Protocol: reads the PreToolUse payload on stdin; emits a JSON permissionDecision
of "deny" or "ask" on a match; otherwise exits 0 silently.
"""

import json
import os
import re
import sys

SPLIT = re.compile(r"&&|\|\||[;|\n]")
WS = re.compile(r"\s+")


def load_config() -> dict:
    root = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    path = os.path.join(root, ".claude", "gate-config.json")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            cfg = json.load(fh)
    except Exception:
        return {"deny": [], "ask": []}
    return {"deny": list(cfg.get("deny", [])), "ask": list(cfg.get("ask", []))}


def norm(s: str) -> str:
    return WS.sub(" ", s.strip())


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # malformed input → don't block

    if payload.get("tool_name") != "Bash":
        return 0

    command = (payload.get("tool_input") or {}).get("command", "") or ""
    cfg = load_config()
    deny, ask = cfg["deny"], cfg["ask"]
    if not deny and not ask:
        return 0

    for raw in SPLIT.split(command):
        seg = norm(raw)
        if not seg:
            continue
        for pat in deny:
            if norm(pat) in seg:
                return decide("deny", f"`{pat}` is forbidden by the project's PIPELINE.md gate.")
        for pat in ask:
            if norm(pat) in seg:
                return decide("ask", f"`{pat}` is a gated command — confirm first (PIPELINE.md gate).")

    return 0


def decide(decision: str, reason: str) -> int:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": decision,
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
