#!/usr/bin/env python3
"""PreToolUse TDD gate — generic, profile-driven, opt-in.

Confirms-first (never hard-denies) when an agent is about to Write/Edit a piece
of PRODUCTION code for which no test file can be found — nudging the strict
red→green→refactor contract in PIPELINE.md §Testing at tool-call time, instead of
relying only on the review agent to catch untested surface after the fact.

Config lives in `.claude/gate-config.json` (generated by /init-pipeline from the
PIPELINE.md `tdd` block), alongside the deny/ask lists gate.py reads:

    { "deny": [...], "ask": [...],
      "tdd": {
        "enforce": true,                 # master switch — false/absent ⇒ hook is silent
        "prod_exts": ["ts","tsx","py","go","rs"],   # extensions that count as production code
        "test_roots": ["apps/api", "apps/web/src"],  # dirs to search for a matching test (optional)
        "skip_globs": ["**/*.d.ts", "**/migrations/**", "**/*.config.*"]  # never gated
      } }

A production file `Foo.ts` PASSES when any file named like a test for it
(`Foo.test.*`, `Foo.spec.*`, `foo_test.*`, `test_foo.*`, `FooTest.*`, `FooTests.*`,
`FooSpec.*`) already exists under a `test_roots` dir (or anywhere in the repo if no
roots are configured). If none is found, the hook emits a permissionDecision of
"ask" so the human can confirm (e.g. writing the failing test in the same step) —
it is deliberately NOT a hard block. Editing a file that is itself a test, or that
matches a skip glob / a non-production extension, is always allowed.

If the config is missing, unreadable, or `tdd.enforce` is not true, the hook stays
silent (exit 0). Same contract as gate.py.
"""

import fnmatch
import json
import os
import sys

# Base-name → test-file patterns. `{b}` is the production file's base name (no ext),
# `{bl}` its lower-case form (Python/Go style test files are conventionally lower-case).
TEST_PATTERNS = (
    "{b}.test.*", "{b}.spec.*",
    "{b}_test.*", "test_{b}.*",
    "{bl}_test.*", "test_{bl}.*",
    "{b}Test.*", "{b}Tests.*", "{b}Spec.*", "{b}Specs.*",
)

# Directories never worth walking when hunting for a test file.
PRUNE = {".git", "node_modules", "dist", "build", "out", "target",
         ".venv", "venv", "__pycache__", ".next", "coverage", ".turbo"}


def load_tdd(root: str) -> dict:
    path = os.path.join(root, ".claude", "gate-config.json")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            cfg = json.load(fh)
    except Exception:
        return {}
    tdd = cfg.get("tdd") if isinstance(cfg, dict) else None
    return tdd if isinstance(tdd, dict) else {}


def is_test_file(base: str, exts: tuple) -> bool:
    """True if `base` (a file's own base name) already looks like a test file."""
    low = base.lower()
    return (
        low.endswith(("test", "tests", "spec", "specs"))
        or low.startswith("test_")
        or ".test" in base or ".spec" in base
    )


def find_test(root: str, roots: list, base: str) -> bool:
    """Does a test file for `base` exist under any search root?"""
    pats = tuple(p.format(b=base, bl=base.lower()) for p in TEST_PATTERNS)
    search = [os.path.join(root, r) for r in roots] if roots else [root]
    for start in search:
        if not os.path.isdir(start):
            continue
        for dirpath, dirnames, filenames in os.walk(start):
            dirnames[:] = [d for d in dirnames if d not in PRUNE]
            for name in filenames:
                if any(fnmatch.fnmatch(name, pat) for pat in pats):
                    return True
    return False


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # malformed input → don't block

    if payload.get("tool_name") not in ("Write", "Edit", "MultiEdit"):
        return 0

    root = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    tdd = load_tdd(root)
    if not tdd.get("enforce"):
        return 0

    file_path = (payload.get("tool_input") or {}).get("file_path", "") or ""
    if not file_path:
        return 0

    rel = os.path.relpath(file_path, root) if os.path.isabs(file_path) else file_path
    name = os.path.basename(rel)
    ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""

    prod_exts = tuple(e.lower().lstrip(".") for e in tdd.get("prod_exts", []))
    if prod_exts and ext not in prod_exts:
        return 0

    for glob in tdd.get("skip_globs", []):
        if fnmatch.fnmatch(rel, glob) or fnmatch.fnmatch(name, glob):
            return 0

    base = name[: -(len(ext) + 1)] if ext else name
    if is_test_file(base, prod_exts):
        return 0  # the file being written IS a test — always fine

    roots = list(tdd.get("test_roots", []))
    if find_test(root, roots, base):
        return 0  # a test for this module already exists

    return decide(
        "ask",
        f"TDD gate: no test found for `{rel}`. Per PIPELINE.md §Testing, write the "
        f"failing test first (red → green). Confirm to proceed anyway.",
    )


def decide(decision: str, reason: str) -> int:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": decision,
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
